name: CI
on: push

jobs:
  tests:
    name: Tests (Rust ${{ matrix.rustup-toolchain }}, Ruby ${{ matrix.ruby-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rustup-toolchain:
          - stable
          - "1.51"
        ruby-version:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Ruby and Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1.0.2
        with:
          rustup-toolchain: ${{ matrix.rustup-toolchain }}
          ruby-version: ${{ matrix.ruby-version }}
          cache-version: v2
          cargo-cache: true

      - uses: Swatinem/rust-cache@v1

      - name: Run tests
        run: cargo test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Run Clippy
        run: cargo clippy --no-deps -- -D warnings
